<?php
/**
 * Implements hook_enable().
 */
function offer_reports_enable() {
  _offer_content_node_setup();
}

/**
 * Implements hook_menu().
 */
function offer_reports_menu() {
  $items['offer'] = array(
    'description' => t('Placeholder for Betsson Offer Page'),
    'page callback' => '_offer_page',
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function offer_reports_preprocess_page(&$vars, $hook) {

  drupal_add_library('system', 'jquery.cookie');
  drupal_add_css(drupal_get_path('module', 'offer_reports') . '/css/offer-report.css');
  drupal_add_js(drupal_get_path('module', 'offer_reports') . '/js/offer-report.js', array(
    'requires_jquery' => TRUE
  ));

  if(isset($_COOKIE['agree_offer_report'])
    && $_COOKIE['agree_offer_report'] == '1'
      && current_path() != 'offer-reports')
      drupal_goto('/offer-reports');

  if(current_path() == 'offer-reports'
      && (!isset($_COOKIE['agree_offer_report'])
          || $_COOKIE['agree_offer_report'] != '1'))
      drupal_goto('/offer');

}

/**
 * Implements hook_node_info().
 */
function offer_reports_node_info() {
  return array(
    'offer_reports' => array(
      'name'  => t('Offer Reports'),
      'description' => t('Used to add Offer Reports relating to Betsson Offer 2017'),
      'base' => t('offer_reports'),
      'has_title' => TRUE,
      'title_label' => t('Offer Report Title')
    )
  );
}

/**
 * Implements hook_form().
 */
function offer_reports_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_block_info().
 */
function offer_reports_block_info() {
  $blocks['offer_page_content'] = array(
    'info'  => t('Offer Page Content (offer_reports.module)'),
    'status' => TRUE,
    'region' => 'content',
    'pages'  => 'offer',
    'cache'  => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_LISTED
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function offer_reports_block_view($delta = '') {
  if($delta == 'offer_page_content') {
     $block['content'] = _offer_page_content();
     return $block;
  }
}

/**
 * Implementation of hook_views_api
 */
function offer_reports_views_api(){
  return array(
    'api' => 3
  );
}

/**
 * Implements hook_views_default_views().
 */
function offer_reports_views_default_views() {
  $offerReport = require('inc/views/offer-report.inc');
  return array(
    $offerReport->name => $offerReport
  );
}

/*
 * Used to create new page
 */
function _offer_page() {
  return array(
    '#markup' => '',
  );
}

function _offer_page_content() {
  $getNode = node_load(variable_get('offer_report_node_id',''));
  $node_view = node_view($getNode,'full');
  $node_view['body'][0]['#suffix'] = _offer_page_buttons();
  drupal_set_title($getNode->title);
  return drupal_render($node_view);
}

function _offer_content_node_setup() {
  create_offer_node();
}

function _offer_page_buttons() {
  return t('<p id="agree_term_container"><a class="button" id="agree_terms" href="#">Accept</a><a class="button" id="exit_terms" href="#">Decline</a></p>');
}

function create_offer_node() {
  global $user;

  $node = new stdClass();
  $node->title = "Offer Page Content Block";
  $node->type = "page";
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
  $node->uid = $user->uid;
  $node->status = 1; //(1 or 0): published or not
  $node->promote = 0; //(1 or 0): promoted to front page
  $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write

  // 'node' is default,
  // Other possible values are "user" and  "taxonomy_term"

  $node = node_submit($node); // Prepare node for saving
  node_save($node);

  variable_set('offer_report_node_id', $node->nid);
}